# errors/error_codes.py
#
# Complete IB TWS API error code registry.
# Source: https://ibkrcampus.com/campus/ibkr-api-page/twsapi-doc/#error-handling

from __future__ import annotations

# Imported lazily to avoid circular imports — use string literals here
# and let error_classifier.py do the severity mapping.

# ---------------------------------------------------------------------------
# Registry: code -> (message, notes)
# Notes may be empty string if not provided in documentation.
# ---------------------------------------------------------------------------

ERROR_CODES: dict[int, tuple[str, str]] = {

    # ------------------------------------------------------------------
    # 100-199: Order and market data errors
    # ------------------------------------------------------------------
    100: ("Max rate of messages per second has been exceeded.",
          "Client has exceeded 50 messages/second. TWS may disconnect."),
    101: ("Max number of tickers has been reached.",
          "Active market data subscriptions exceeded. Check Ctrl-Alt-= in TWS."),
    102: ("Duplicate ticker ID.",
          "A market data request used a ticker ID already in use."),
    103: ("Duplicate order ID.",
          "Order placed with ID <= previous order ID from this client."),
    104: ("Can't modify a filled order.",
          "Attempted to modify an order already filled by the system."),
    105: ("Order being modified does not match original order.",
          "Basic parameters differ from original aside from quantity or price."),
    106: ("Can't transmit order ID.",
          "Usually caused by invalid order type or formatting."),
    107: ("Cannot transmit incomplete order.",
          "Order is missing a required field."),
    109: ("Price is out of the range defined by the Percentage setting at order defaults frame.",
          "Price outside range set in TWS Order Precautionary Settings."),
    110: ("The price does not conform to the minimum price variation for this contract.",
          "Price has more precision than allowed. Check IB Contracts and Securities Search."),
    111: ("The TIF and the order type are incompatible.",
          "Time in force cannot be used with this order type."),
    113: ("The Tif option should be set to DAY for MOC and LOC orders.",
          "Market-on-close or Limit-on-close must use TIF=DAY."),
    114: ("Relative orders are valid for stocks only.", "Deprecated."),
    115: ("Relative orders for US stocks can only be submitted to SMART, SMART_ECN, INSTINET, or PRIMEX.", "Deprecated."),
    116: ("The order cannot be transmitted to a dead exchange.",
          "Exchange field is invalid."),
    117: ("The block order size must be at least 50.",
          "Block order submitted with quantity < 50."),
    118: ("VWAP orders must be routed through the VWAP exchange.", ""),
    119: ("Only VWAP orders may be placed on the VWAP exchange.", ""),
    120: ("It is too late to place a VWAP order for today.",
          "Cutoff has passed for VWAP orders today."),
    121: ("Invalid BD flag for the order.", "Deprecated."),
    122: ("No request tag has been found for order.", "Request encoding improperly formed."),
    123: ("No record is available for conid.", "Deprecated."),
    124: ("No market rule is available for conid.",
          "May occur when interacting with a non-tradeable instrument such as an Index."),
    125: ("Buy price must be the same as the best asking price.",
          "Buy order exceptionally above Best Ask. Request market data for NBO."),
    126: ("Sell price must be the same as the best bidding price.",
          "Sell order exceptionally below Best Bid. Request market data for NBB."),
    129: ("VWAP orders must be submitted at least three minutes before the start time.", ""),
    131: ("The sweep-to-fill flag and display size are only valid for US stocks routed through SMART.",
          "Sweep-to-fill used on unsupported order type."),
    132: ("This order cannot be transmitted without a clearing account.", ""),
    133: ("Submit new order failed.",
          "Failure in order submission. Check parameters or connectivity."),
    134: ("Modify order failed.",
          "Order may have been executed or cancelled. Request open orders to verify."),
    135: ("Can't find order with ID.",
          "Attempt to cancel order not currently in the system."),
    136: ("This order cannot be cancelled.", "Order is not in a cancellable state."),
    137: ("VWAP orders can only be cancelled up to three minutes before the start time.", ""),
    138: ("Could not parse ticker request.",
          "Invalid symbols or content in ticker symbol."),
    139: ("Parsing error.", "Error in command syntax."),
    140: ("The size value should be an integer.",
          "Size field in Order class has invalid type."),
    141: ("The price value should be a double.",
          "A price field in Order class has invalid type."),
    142: ("Institutional customer account does not have account info.", ""),
    143: ("Requested ID is not an integer number.",
          "IDs used in API requests must be integer values."),
    144: ("Order size does not match total share allocation.", ""),
    145: ("Error in validating entry fields.", "Error with syntax of a request field."),
    146: ("Invalid trigger method.",
          "Trigger method for stop or trail stop not one of the allowable methods."),
    147: ("The conditional contract info is incomplete.", ""),
    148: ("Conditional submission of orders is supported for Limit, Market, MidPrice, Relative and Snap order types only.", ""),
    151: ("This order cannot be transmitted without a user name.", ""),
    152: ("The 'hidden' order attribute may not be specified for this order.", ""),
    153: ("EFPs can only be limit orders.", "Deprecated."),
    154: ("Orders cannot be transmitted for a halted security.",
          "Security was halted when order was placed."),
    155: ("A sizeOp order must have a user name and account.", "Deprecated."),
    156: ("A SizeOp order must go to IBSX.", "Deprecated."),
    157: ("An order can be EITHER Iceberg or Discretionary.",
          "Iceberg and Discretionary fields cannot both be set."),
    158: ("You must specify an offset amount or a percent offset value.",
          "TRAIL and TRAIL STOP require absolute offset or offset percentage."),
    159: ("The percent offset value must be between 0% and 100%.", ""),
    160: ("The size value cannot be zero.",
          "Order size must be a positive quantity."),
    161: ("Cancel attempted when order is not in a cancellable state.",
          "Attempt to cancel inactive order."),
    162: ("Historical market data Service error message.", ""),
    163: ("The price specified would violate the percentage constraint specified in the default order settings.",
          "Order price outside allowable range in Order Precautionary Settings."),
    164: ("There is no market data to check price percent violations.",
          "No market data available for contract to validate price."),
    165: ("Historical market Data Service query message.",
          "Issue with historical data request, e.g. no data in IB database."),
    166: ("HMDS Expired Contract Violation.",
          "Historical data not available for specified expired contract."),
    167: ("VWAP order time must be in the future.", ""),
    168: ("Discretionary amount does not conform to the minimum price variation for this contract.", ""),

    # ------------------------------------------------------------------
    # 200-299: Contract and security errors
    # ------------------------------------------------------------------
    200: ("No security definition has been found for the request.",
          "Contract does not match any in IB database. Check symbol, secType, exchange, currency, primaryExch."),
    201: ("Order rejected.",
          "Order rejected by IB servers. See Order Placement Considerations."),
    202: ("Order cancelled.",
          "Active order cancelled by IB server."),
    203: ("The security is not available or allowed for this account.",
          "Security has trading restriction with this account."),
    300: ("Can't find EId with ticker Id.",
          "Attempt to cancel market data for ticker ID not associated with current subscription."),
    301: ("Invalid ticker action.", ""),
    302: ("Error parsing stop ticker string.", ""),
    303: ("Invalid action.",
          "Action not available for this account. Typically only BUY or SELL."),
    304: ("Invalid account value action.", ""),
    305: ("Request parsing error, the request has been ignored.",
          "Syntax of DDE request is invalid."),
    306: ("Error processing DDE request.", ""),
    307: ("Invalid request topic.",
          "Topic field in DDE request is invalid."),
    308: ("Unable to create the API page in TWS as the maximum number of pages already exists.", ""),
    309: ("Max number of market depth requests has been reached.",
          "Maximum of 3 distinct market depth requests. See Market Data Line Documentation."),
    310: ("Can't find the subscribed market depth with tickerId.", ""),
    311: ("The origin is invalid.",
          "Origin field in Order class is invalid."),
    312: ("The combo details are invalid.",
          "Combination contract has invalid parameters."),
    313: ("The combo details for leg are invalid.",
          "A combo leg was not defined correctly."),
    314: ("Security type 'BAG' requires combo leg details.",
          "When using secType=BAG add combo legs with details."),
    315: ("Stock combo legs are restricted to SMART order routing.",
          "Specify SMART as exchange for stock combo contracts."),
    316: ("Market depth data has been HALTED. Please re-subscribe.", ""),
    317: ("Market depth data has been RESET. Please empty deep book contents before applying any new entries.", ""),
    319: ("Invalid log level.",
          "Log level must be in range 1-5."),
    320: ("Server error when reading an API client request.", ""),
    321: ("Server error when validating an API client request.",
          "Check all contract and order fields."),
    322: ("Server error when processing an API client request.", ""),
    323: ("Server error.", ""),
    324: ("Server error when reading a DDE client request (missing information).",
          "Specify all needed information for the request."),
    325: ("Discretionary orders are not supported for this combination of exchange and order type.", ""),
    326: ("Unable to connect as the client id is already in use. Retry with a unique client id.",
          "Another client is already connected with this client ID."),
    327: ("Only API connections with clientId set to 0 can set the auto bind TWS orders property.", ""),
    328: ("Trailing stop orders can be attached to limit or stop-limit orders only.", ""),
    329: ("Order modify failed. Cannot change to the new order type.", ""),
    330: ("Only FA or STL customers can request managed accounts list.", ""),
    331: ("Internal error. FA or STL does not have any managed accounts.", ""),
    332: ("The account codes for the order profile are invalid.", ""),
    333: ("Invalid share allocation syntax.", ""),
    334: ("Invalid Good Till Date order.", ""),
    335: ("Invalid delta: The delta must be between 0 and 100.", ""),
    336: ("The time or time zone is invalid.", "Format: hh:mm:ss xxx. E.g. 15:59:00 EST."),
    337: ("The date, time, or time-zone entered is invalid.",
          "Format: yyyymmdd hh:mm:ss xxx. E.g. 20031126 15:59:00 EST."),
    338: ("Good After Time orders are currently disabled on this exchange.", ""),
    339: ("Futures spread are no longer supported. Please use combos instead.", ""),
    340: ("Invalid improvement amount for box auction strategy.", ""),
    341: ("Invalid delta. Valid values are from 1 to 100.", ""),
    342: ("Pegged order is not supported on this exchange.", ""),
    343: ("The date, time, or time-zone entered is invalid.", ""),
    344: ("The account logged into is not a financial advisor account.", ""),
    345: ("Generic combo is not supported for FA advisor account.", ""),
    346: ("Not an institutional account or an away clearing account.", ""),
    347: ("Short sale slot value must be 1 (broker holds shares) or 2 (delivered from elsewhere).", ""),
    348: ("Order not a short sale — type must be SSHORT to specify short sale slot.", ""),
    349: ("Generic combo does not support 'Good After' attribute.", ""),
    350: ("Minimum quantity is not supported for best combo order.", ""),
    351: ("The 'Regular Trading Hours only' flag is not valid for this order.", ""),
    352: ("Short sale slot value of 2 (delivered from elsewhere) requires location.",
          "Specify designatedLocation for the order."),
    353: ("Short sale slot value of 1 requires no location be specified.", ""),
    354: ("Requested market data is not subscribed.",
          "No live market data subscription. Request delayed data or add subscription."),
    355: ("Order size does not conform to market rule.",
          "Check order size parameters from TWS Contract Details."),
    356: ("Smart-combo order does not support OCA group.", ""),
    357: ("Your client version is out of date.", ""),
    358: ("Smart combo child order not supported.", ""),
    359: ("Combo order only supports reduce on fill without block (OCA).", ""),
    360: ("No whatif check support for smart combo order.", ""),
    361: ("Invalid trigger price.", ""),
    362: ("Invalid adjusted stop price.", ""),
    363: ("Invalid adjusted stop limit price.", ""),
    364: ("Invalid adjusted trailing amount.", ""),
    365: ("No scanner subscription found for ticker id.",
          "Scanner request cancelled or not found."),
    366: ("No historical data query found for ticker id.",
          "Historical data request cancelled or not found."),
    367: ("Volatility type if set must be 1 or 2 for VOL orders.", ""),
    368: ("Reference Price Type must be 1 or 2 for dynamic volatility management.", ""),
    369: ("Volatility orders are only valid for US options.", ""),
    370: ("Dynamic Volatility orders must be SMART routed.", ""),
    371: ("VOL order requires positive floating point value for volatility.", ""),
    372: ("Cannot set dynamic VOL attribute on non-VOL order.", ""),
    373: ("Can only set stock range attribute on VOL or RELATIVE TO STOCK order.", ""),
    374: ("If both are set, the lower stock range attribute must be less than the upper.", ""),
    375: ("Stock range attributes cannot be negative.", ""),
    376: ("The order is not eligible for continuous update.", ""),
    377: ("Must specify valid delta hedge order aux. price.", ""),
    378: ("Delta hedge order type requires delta hedge aux. price to be specified.", ""),
    379: ("Delta hedge order type requires that no delta hedge aux. price be specified.", ""),
    380: ("This order type is not allowed for delta hedge orders.",
          "Limit, Market or Relative orders are supported."),
    381: ("Your DDE.dll needs to be upgraded.", ""),
    382: ("The price specified violates the number of ticks constraint specified in the default order settings.", ""),
    383: ("The size specified violates the size constraint specified in the default order settings.", ""),
    384: ("Invalid DDE array request.", ""),
    385: ("Duplicate ticker ID for API scanner subscription.", ""),
    386: ("Duplicate ticker ID for API historical data query.", ""),
    387: ("Unsupported order type for this exchange and security type.", ""),
    388: ("Order size is smaller than the minimum requirement.", ""),
    389: ("Supplied routed order ID is not unique.", ""),
    390: ("Supplied routed order ID is invalid.", ""),
    391: ("The time or time-zone entered is invalid. The correct format is hh:mm:ss xxx.", ""),
    392: ("Invalid order: contract expired.",
          "Cannot place an order for an expired contract."),
    393: ("Short sale slot may be specified for delta hedge orders only.", ""),
    394: ("Invalid Process Time: must be integer number of milliseconds between 100 and 2000.", ""),
    395: ("Due to system problems, orders with OCA groups are currently not being accepted.", ""),
    396: ("Due to system problems, application is currently accepting only Market and Limit orders.", ""),
    397: ("Due to system problems, application is currently accepting only Market and Limit orders.", ""),
    398: ("cannot be used as a condition trigger.", ""),
    399: ("Order message error.", ""),
    400: ("Algo order error.", ""),
    401: ("Length restriction.", ""),
    402: ("Conditions are not allowed for this contract.", ""),
    403: ("Invalid stop price.",
          "Stop Price is invalid for this contract."),
    404: ("Shares for this order are not immediately available for short sale.",
          "Order held while locating shares."),
    405: ("The child order quantity should be equivalent to the parent order size.", "Deprecated."),
    406: ("The currency is not allowed.", "Specify a valid currency."),
    407: ("The symbol should contain valid non-unicode characters only.", ""),
    408: ("Invalid scale order increment.", ""),
    409: ("Invalid scale order. You must specify order component size.", ""),
    410: ("Invalid subsequent component size for scale order.", ""),
    411: ("The 'Outside Regular Trading Hours' flag is not valid for this order.", ""),
    412: ("The contract is not available for trading.", ""),
    413: ("What-if order should have the transmit flag set to true.", ""),
    414: ("Snapshot market data subscription is not applicable to generic ticks.", ""),
    415: ("Wait until previous RFQ finishes and try again.", ""),
    416: ("RFQ is not applicable for the contract.", ""),
    417: ("Invalid initial component size for scale order.", ""),
    418: ("Invalid scale order profit offset.", ""),
    419: ("Missing initial component size for scale order.", ""),
    420: ("Invalid real-time query.",
          "Possible pacing violation."),
    421: ("Invalid route.", "Deprecated."),
    422: ("The account and clearing attributes on this order may not be changed.", ""),
    423: ("Cross order RFQ has been expired.", ""),
    424: ("FA Order requires allocation to be specified.", "Deprecated."),
    425: ("FA Order requires per-account manual allocations.", "Deprecated."),
    426: ("None of the accounts have enough shares.",
          "Cannot enter short position — no short sale available."),
    427: ("Mutual Fund order requires monetary value to be specified.", "Deprecated."),
    428: ("Mutual Fund Sell order requires shares to be specified.", "Deprecated."),
    429: ("Delta neutral orders are only supported for combos (BAG security type).", ""),
    430: ("Fundamentals data for the security specified is not available.", ""),
    431: ("What to show field is missing or incorrect.", "Deprecated."),
    432: ("Commission must not be negative.", "Deprecated."),
    433: ("Invalid 'Restore size after taking profit' for multiple account allocation scale order.", ""),
    434: ("The order size cannot be zero.", ""),
    435: ("You must specify an account.", "Function only works on a single account."),
    436: ("You must specify an allocation (either a single account, group, or profile).", ""),
    437: ("Order can have only one flag Outside RTH or Allow PreOpen.", "Deprecated."),
    438: ("The application is now locked.", "Deprecated."),
    439: ("Order processing failed. Algorithm definition not found.",
          "Check AlgoStrategy and AlgoParams."),
    440: ("Order modify failed. Algorithm cannot be modified.", ""),
    441: ("Algo attributes validation failed.",
          "Check AlgoStrategy and AlgoParams."),
    442: ("Specified algorithm is not allowed for this order.", ""),
    443: ("Order processing failed. Unknown algo attribute.",
          "AlgoParams specification is incorrect."),
    444: ("Volatility Combo order is not yet acknowledged. Cannot submit changes at this time.", ""),
    445: ("The RFQ for this order is no longer valid.", ""),
    446: ("Missing scale order profit offset.", ""),
    447: ("Missing scale price adjustment amount or interval.", ""),
    448: ("Invalid scale price adjustment interval.", ""),
    449: ("Unexpected scale price adjustment amount or interval.", ""),
    481: ("Order size reduced.", ""),

    # ------------------------------------------------------------------
    # 501-589: Client-side connection and sending errors
    # ------------------------------------------------------------------
    501: ("Already Connected.",
          "Client application is already connected to TWS."),
    502: ("Couldn't connect to TWS.",
          "Enable 'ActiveX and Socket Clients' in TWS API Settings and verify port."),
    503: ("The TWS is out of date and must be upgraded.",
          "TWS/IBG version too old for current API version."),
    504: ("Not connected.",
          "Request made without connecting or after connection was broken."),
    505: ("Fatal Error: Unknown message id.", ""),
    506: ("Unsupported Version.", "Not used in Python client."),
    507: ("Bad Message Length.",
          "EOF exception while reading from socket. ClientId may be in use or TWS closed."),
    508: ("Bad Message.", ""),
    509: ("Exception caught while reading socket.", "Not used in Python client."),
    510: ("Request Market Data Sending Error.", ""),
    511: ("Cancel Market Data Sending Error.", ""),
    512: ("Order Sending Error.", ""),
    513: ("Account Update Request Sending Error.", ""),
    514: ("Request For Executions Sending Error.", ""),
    515: ("Cancel Order Sending Error.", ""),
    516: ("Request Open Order Sending Error.", ""),
    517: ("Unknown contract. Verify the contract details supplied.", "Not used in Python client."),
    518: ("Request Contract Data Sending Error.", ""),
    519: ("Request Market Depth Sending Error.", ""),
    520: ("Failed to create socket.", "Not used in C# client."),
    521: ("Set Server Log Level Sending Error.", ""),
    522: ("FA Information Request Sending Error.", ""),
    523: ("FA Information Replace Sending Error.", ""),
    524: ("Request Scanner Subscription Sending Error.", ""),
    525: ("Cancel Scanner Subscription Sending Error.", ""),
    526: ("Request Scanner Parameter Sending Error.", ""),
    527: ("Request Historical Data Sending Error.", ""),
    528: ("Request Historical Data Sending Error.", ""),
    529: ("Request Real-time Bar Data Sending Error.", ""),
    530: ("Cancel Real-time Bar Data Sending Error.", ""),
    531: ("Request Current Time Sending Error.", ""),
    532: ("Request Fundamental Data Sending Error.", ""),
    533: ("Cancel Fundamental Data Sending Error.", ""),
    534: ("Request Calculate Implied Volatility Sending Error.", ""),
    535: ("Request Calculate Option Price Sending Error.", ""),
    536: ("Cancel Calculate Implied Volatility Sending Error.", ""),
    537: ("Cancel Calculate Option Price Sending Error.", ""),
    538: ("Request Global Cancel Sending Error.", ""),
    539: ("Request Market Data Type Sending Error.", ""),
    540: ("Request Positions Sending Error.", ""),
    541: ("Cancel Positions Sending Error.", ""),
    542: ("Request Account Data Sending Error.", ""),
    543: ("Cancel Account Data Sending Error.", ""),
    544: ("Verify Request Sending Error.", ""),
    545: ("Verify Message Sending Error.", ""),
    546: ("Query Display Groups Sending Error.", ""),
    547: ("Subscribe To Group Events Sending Error.", ""),
    548: ("Update Display Group Sending Error.", ""),
    549: ("Unsubscribe From Group Events Sending Error.", ""),
    550: ("Start API Sending Error.", ""),
    551: ("Verify And Auth Request Sending Error.", ""),
    552: ("Verify And Auth Message Sending Error.", ""),
    553: ("Request Positions Multi Sending Error.", ""),
    554: ("Cancel Positions Multi Sending Error.", ""),
    555: ("Request Account Updates Multi Sending Error.", ""),
    556: ("Cancel Account Updates Multi Sending Error.", ""),
    557: ("Request Security Definition Option Params Sending Error.", ""),
    558: ("Request Soft Dollar Tiers Sending Error.", ""),
    559: ("Request Family Codes Sending Error.", ""),
    560: ("Request Matching Symbols Sending Error.", ""),
    561: ("Request Market Depth Exchanges Sending Error.", ""),
    562: ("Request Smart Components Sending Error.", ""),
    563: ("Request News Providers Sending Error.", ""),
    564: ("Request News Article Sending Error.", ""),
    565: ("Request Historical News Sending Error.", ""),
    566: ("Request Head Time Stamp Sending Error.", ""),
    567: ("Request Histogram Data Sending Error.", ""),
    568: ("Cancel Request Histogram Data Sending Error.", ""),
    569: ("Cancel Head Time Stamp Sending Error.", ""),
    570: ("Request Market Rule Sending Error.", ""),
    571: ("Request PnL Sending Error.", ""),
    572: ("Cancel PnL Sending Error.", ""),
    573: ("Request PnL Single Error.", ""),
    574: ("Cancel PnL Single Sending Error.", ""),
    575: ("Request Historical Ticks Error.", ""),
    576: ("Request Tick-By-Tick Data Sending Error.", ""),
    577: ("Cancel Tick-By-Tick Data Sending Error.", ""),
    578: ("Request Completed Orders Sending Error.", ""),
    579: ("Invalid symbol in string.", ""),
    580: ("Request WSH Meta Data Sending Error.", ""),
    581: ("Cancel WSH Meta Data Sending Error.", ""),
    582: ("Request WSH Event Data Sending Error.", ""),
    583: ("Cancel WSH Event Data Sending Error.", ""),
    584: ("Request User Info Sending Error.", ""),
    585: ("FA Profile is not supported anymore, use FA Group instead.",
          "FaDataTypeEnum.PROFILES is deprecated. Use FaDataTypeEnum.GROUPS."),
    586: ("Failed to read message because not connected.", "Java client only."),
    587: ("Request Current Time In Millis Sending Error.", ""),
    588: ("Error encoding protobuf.", "Java client only."),
    589: ("Cancel Market Depth Sending Error.", ""),

    # ------------------------------------------------------------------
    # 1100-1300: System connectivity codes
    # ------------------------------------------------------------------
    1100: ("Connectivity between IB and the TWS has been lost.",
           "Internet connectivity issue, nightly reset, or competing session."),
    1101: ("Connectivity between IB and TWS has been restored — data lost.",
           "Market data requests lost. Re-submit all subscriptions."),
    1102: ("Connectivity between IB and TWS has been restored — data maintained.",
           "Market data requests recovered. No action needed."),
    1300: ("TWS socket port has been reset and this connection is being dropped.",
           "Port changed during active API connection. Reconnect on new port."),

    # ------------------------------------------------------------------
    # 2100-2169: TWS notification codes (warnings / info)
    # ------------------------------------------------------------------
    2100: ("New account data requested from TWS. API client has been unsubscribed from account data.",
           "Only one reqAccountUpdates at a time. New request overrides old."),
    2101: ("Unable to subscribe to account as the following clients are subscribed to a different account.",
           "Active subscription started by different client rejected new request."),
    2102: ("Unable to modify this order as it is still being processed.",
           "Wait until order fully processed before modifying."),
    2103: ("A market data farm is disconnected.",
           "Connectivity problem to IB server. Usually ISP issue."),
    2104: ("Market data farm connection is OK.",
           "Notification that connection to market data server is OK. Expected on connect."),
    2105: ("A historical data farm is disconnected.",
           "Connectivity problem to IB server. Usually ISP issue."),
    2106: ("A historical data farm is connected.",
           "Notification that connection to historical data server is OK."),
    2107: ("A historical data farm connection has become inactive but should be available upon demand.",
           "Connection dormant — no active historical data requests. Not an error."),
    2108: ("A market data farm connection has become inactive but should be available upon demand.",
           "Connection dormant — not needed currently. Safe to ignore."),
    2109: ("Order Event Warning: Attribute 'Outside Regular Trading Hours' is ignored.",
           "outsideRth flag set for order with no RTH/non-RTH distinction."),
    2110: ("Connectivity between TWS and server is broken. It will be restored automatically.",
           "Usually occurs during IB nightly server reset."),
    2111: ("The Start and/or End Time for algo order was adjusted to use the next trading date.",
           "Go to TWS Global Configuration > Orders > Settings to correct."),
    2119: ("Market data farm is connecting.", ""),
    2130: ("Warning: products are trading on the basis of currency price with factor.", ""),
    2137: ("Cross Side Warning.",
           "Order will change position from long to short or short to long."),
    2152: ("Market depth smart depth exchanges.", ""),
    2158: ("Sec-def data farm connection is OK.",
           "Notification that connection to security definition server is OK. Expected on connect."),
    2168: ("EtradeOnly order attribute is no longer supported.",
           "Remove EtradeOnly attribute. Error received with TWS versions 983+."),
    2169: ("firmQuoteOnly order attribute is no longer supported.",
           "Remove firmQuoteOnly attribute. Error received with TWS versions 983+."),
    2174: ("Date-time submitted without explicit timezone.",
           "Use YYYYMMDD-HH:MM:SS format for UTC datetime strings."),

    # ------------------------------------------------------------------
    # 10000-10349: Extended TWS error codes
    # ------------------------------------------------------------------
    10000: ("Cross currency combo error.", ""),
    10001: ("Cross currency vol error.", ""),
    10002: ("Invalid non-guaranteed legs.", ""),
    10003: ("IBSX not allowed.", ""),
    10005: ("Read-only models.", ""),
    10006: ("Missing parent order.",
            "Parent order ID not found. Add 50ms delay before placing child orders."),
    10007: ("Invalid hedge type.", ""),
    10008: ("Invalid beta value.", ""),
    10009: ("Invalid hedge ratio.", ""),
    10010: ("Invalid delta hedge order.", ""),
    10011: ("Currency is not supported for Smart combo.", ""),
    10012: ("Invalid allocation percentage.", "FaPercentage specified is not valid."),
    10013: ("Smart routing API error (Smart routing opt-out required).", ""),
    10014: ("PctChange limits.", "Deprecated."),
    10015: ("Trading is not allowed in the API.", ""),
    10016: ("Contract is not visible.", "Deprecated."),
    10017: ("Contracts are not visible.", "Deprecated."),
    10018: ("Orders use EV warning.", ""),
    10019: ("Trades use EV warning.", ""),
    10020: ("Display size should be smaller than order size.",
            "Display size must be smaller than total quantity."),
    10021: ("Invalid leg2 to Mkt Offset API.", "Deprecated."),
    10022: ("Invalid Leg Prio API.", "Deprecated."),
    10023: ("Invalid combo display size API.", "Deprecated."),
    10024: ("Invalid don't start next legin API.", "Deprecated."),
    10025: ("Invalid leg2 to Mkt time1 API.", "Deprecated."),
    10026: ("Invalid leg2 to Mkt time2 API.", "Deprecated."),
    10027: ("Invalid combo routing tag API.", "Deprecated."),
    10089: ("Market data not subscribed. Delayed market data available.",
            "No live subscription for this instrument. Request delayed data."),
    10090: ("Part of requested market data is not subscribed.",
            "Some tick types require additional subscriptions. Greeks may be unavailable."),
    10091: ("Market data not subscribed. Delayed market data available.",
            "See TWS vs API Data for more details."),
    10147: ("Order to be canceled was not found.", ""),
    10148: ("OrderId that needs to be cancelled cannot be cancelled.",
            "Order already filled by the system."),
    10186: ("Requested market data is not subscribed. Delayed market data is not enabled.",
            "See Market Data Types on how to enable delayed data."),
    10187: ("Failed to request historical ticks: No market data permissions.", ""),
    10189: ("Failed to request tick-by-tick data. Invalid Real-time Query.",
            "TWS connected from different IP, or no market data permissions."),
    10197: ("No market data during competing session.",
            "Paper and live accounts logged in simultaneously. Live account gets priority."),
    10225: ("Bust event occurred, current subscription is deactivated.",
            "Please resubscribe real-time bars immediately."),
    10230: ("You have unsaved FA changes.",
            "Pending Financial Advisor configuration changes."),
    10231: ("The following Groups and/or Profiles contain invalid accounts.", ""),
    10233: ("Defaults were inherited from CASH preset during the creation of this order.", ""),
    10234: ("The Decision Maker field is required and not set for this order.", ""),
    10235: ("The Decision Maker field is required and not set for this order (ibbot).", ""),
    10236: ("Child has to be AON if parent order is AON.", ""),
    10237: ("All or None ticket can route entire unfilled size only.", ""),
    10238: ("Some error occurred during communication with Advisor Setup web-app.", ""),
    10239: ("This order will affect accounts flagged for risk score criteria.", ""),
    10240: ("You must enter a valid Price Cap.", ""),
    10241: ("Order Quantity is expressed in monetary terms. Modification not supported via API.", ""),
    10242: ("Fractional-sized order cannot be modified via API.", ""),
    10243: ("Fractional-sized order cannot be placed via API.",
            "Use desktop version to place this order."),
    10244: ("Cash Quantity cannot be used for this order.", ""),
    10245: ("This financial instrument does not support fractional shares trading.", ""),
    10246: ("This order doesn't support fractional shares trading.", ""),
    10247: ("Only IB SmartRouting supports fractional shares.", ""),
    10248: ("Doesn't have permission to trade fractional shares.", ""),
    10249: ("Order doesn't support fractional shares.", ""),
    10250: ("The size does not conform to the minimum variation for this contract.", ""),
    10251: ("Fractional shares are not supported for allocation orders.", ""),
    10252: ("This non-close-position order doesn't support fractional shares trading.", ""),
    10253: ("Clear Away orders are not supported for multi-leg combo with attached hedge.", ""),
    10254: ("Invalid Order: bond expired.", ""),
    10268: ("The 'EtradeOnly' order attribute is not supported.",
            "Remove EtradeOnly attribute. TWS versions 983+."),
    10269: ("The 'firmQuoteOnly' order attribute is not supported.",
            "Remove firmQuoteOnly attribute. TWS versions 983+."),
    10270: ("The 'nbboPriceCap' order attribute is not supported.",
            "Remove nbboPriceCap attribute. TWS versions 983+."),
    10276: ("News feed is not allowed.",
            "API client not permissioned for WSH news feed."),
    10277: ("News feed permissions required.",
            "API client not subscribed for WSH news feed."),
    10278: ("Duplicate WSH metadata request.",
            "Request already pending for same API client."),
    10279: ("Failed request WSH metadata.", ""),
    10280: ("Failed cancel WSH metadata.", ""),
    10281: ("Duplicate WSH event data request.",
            "Request already pending for same API client."),
    10282: ("WSH metadata not requested.",
            "Must send reqWshMetaData before requesting event data."),
    10283: ("Fail request WSH event data.", ""),
    10284: ("Fail cancel WSH event data.", ""),
    10285: ("Your API version does not support fractional sizing rules.",
            "Please upgrade to at least version 163."),
    10286: ("Field cannot contain more than the specified number of decimals.", ""),
    10287: ("Cryptocurrency order is not confirmed.", ""),
    10288: ("Market order confirmation dialog for cryptocurrencies.", ""),
    10289: ("You must set Cash Quantity for this order.", ""),
    10290: ("This order only supports CashQty trading.", ""),
    10291: ("Orders to harvest Capital Loss must use the DAY time-in-force.", ""),
    10292: ("Order type/action restriction.", ""),
    10293: ("Cryptocurrency Cash Quantity order cannot specify size.", ""),
    10294: ("Cash quantity set on the order does not match total monetary amount of the Group.", ""),
    10295: ("Orders to harvest Capital Loss must use the DAY time-in-force.", ""),
    10296: ("Smart Routing features 'Seek Price Improvement' and 'Do not route to Dark Pools' are mutually exclusive.", ""),
    10297: ("Not Held attribute is invalid for this order.", ""),
    10298: ("Cannot trade an instrument with currency different from model currency.", ""),
    10299: ("Expected what to show is different from specified.", ""),
    10300: ("The date/time format is invalid.", ""),
    10301: ("The date/time format is invalid.", ""),
    10302: ("Min trade quantity is not allowed for this order.", ""),
    10303: ("Invalid min trade quantity value. Must be a positive integer not exceeding total order size.", ""),
    10304: ("Minimum Competing Size value must be non-negative.", ""),
    10305: ("Compete against best bid or offer Offset dollar value must be positive multiple of a cent.", ""),
    10306: ("Mid offsets are not allowed.", ""),
    10307: ("Invalid MidOffsetAtWhole and/or MidOffsetAtHalf attribute values.", ""),
    10308: ("Revision to Post to ATS value presence is not allowed.", ""),
    10309: ("Invalid WSH event data request.", ""),
    10310: ("The Solicited field should be used for orders initiated or recommended by the broker.", ""),
    10311: ("This order will be directly routed. Direct routed orders may result in higher trade fees.", ""),
    10312: ("The order type Volatility is not supported for this combination of instrument and account type.", ""),
    10314: ("The date/time format is invalid.",
            "Use YYYYMMDD-HH:MM:SS for UTC or YYYYMMDD HH:MM:SS TZ format."),
    10315: ("The time entered is invalid. Format: hh:mm:ss in UTC.", ""),
    10316: ("Trigger Outside RTH was deprecated.", "Use Outside RTH attribute instead."),
    10317: ("The Cash Quantity size does not conform to minimum variation.", ""),
    10318: ("This order doesn't support fractional quantity trading.", ""),
    10319: ("Placing orders for Municipal Bonds via API is currently disabled.", ""),
    10321: ("Placing orders for Municipal Bonds is currently disabled for attached and OCA orders.", ""),
    10322: ("This API request for All is not supported for Dynamic Account Addition.", ""),
    10324: ("Invalid parameters for OCA group for exchange. Overfill Protection is implied.", ""),
    10325: ("OCA group is not supported.", ""),
    10326: ("OCA group revision is not allowed.", ""),
    10327: ("OCA group type revision is not allowed.", ""),
    10328: ("Connection lost, order data could not be resolved.", ""),
    10329: ("This order will be directly routed.", ""),
    10330: ("The expiry date/time format is invalid.",
            "Format: yyyyMM, yyyyMMdd HH:mm:ss, or yyyyMMdd-HH:mm:ss (UTC)."),
    10331: ("Any stop warning.", ""),
    10332: ("Cryptocurrency volatility warning.", ""),
    10333: ("Option Exercise at-the-money warning.", ""),
    10334: ("Confirm Omnibus Order Account.", ""),
    10335: ("Order presets cannot be applied as configured.", ""),
    10336: ("Per-leg executing broker configuration is not supported.", ""),
    10337: ("Misc options key is invalid in request.", ""),
    10338: ("Misc options value is invalid for key in request.", ""),
    10339: ("Setting end date/time for continuous future security type is not allowed.", ""),
    10340: ("The following order attribute is not supported.", ""),
    10341: ("Parent order id cannot be modified.", ""),
    10342: ("The 'ImbalanceOnly' order attribute may not be specified for this order.", ""),
    10343: ("Selling Event Contracts is neither allowed directly nor as an attached profit taker.", ""),
    10344: ("Price value must be between 0.02 and 0.99 with a maximum of two decimal places.", ""),
    10345: ("You cannot trade this security type.", ""),
    10346: ("Market data cannot be delivered because ticker for same instrument is displayed elsewhere.", ""),
    10347: ("This security has limited liquidity.", "Heightened risk of inability to close position."),
}